name: CI

on:
  push:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Sync (install deps)
        run: uv sync
      
      - name: Pytest
        run: uv run pytest

      - name: Black check
        run: uv run black --check .

      - name: Flake8
        run: uv run flake8 .


